export const PROJECTS = [
  {
    id: 'immeuble-residentiel-lille',
    title: 'Immeuble résidentiel — Lille',
    location: 'Lille, Hauts-de-France',
    type: 'Résidentiel',
    surface: '450 m²',
    units: 6,
    status: 'realise',
    buyPrice: '380 000 €',
    worksAmount: '120 000 €',
    sellPrice: '620 000 €',
    duration: '8 mois',
    description: 'Acquisition d\'un immeuble de rapport de 6 lots en centre-ville de Lille. Rénovation complète des parties communes et privatives : isolation thermique, menuiseries, électricité aux normes. Découpe en 6 appartements indépendants revendus à des investisseurs et primo-accédants.',
    images: [],
    featured: true,
  },
  {
    id: 'plateau-mixte-tourcoing',
    title: 'Plateau mixte — Tourcoing',
    location: 'Tourcoing, Hauts-de-France',
    type: 'Mixte',
    surface: '320 m²',
    units: 4,
    status: 'realise',
    buyPrice: '220 000 €',
    worksAmount: '95 000 €',
    sellPrice: '410 000 €',
    duration: '6 mois',
    description: 'Transformation d\'un plateau commercial désaffecté en 3 appartements et 1 local professionnel. Changement de destination, création de planchers, mise aux normes accessibilité pour le local du rez-de-chaussée.',
    images: [],
    featured: true,
  },
  {
    id: 'maison-bourgeoise-roubaix',
    title: 'Maison bourgeoise — Roubaix',
    location: 'Roubaix, Hauts-de-France',
    type: 'Résidentiel',
    surface: '280 m²',
    units: 3,
    status: 'en-cours',
    buyPrice: '190 000 €',
    worksAmount: '110 000 €',
    sellPrice: null,
    duration: null,
    description: 'Division d\'une maison bourgeoise en 3 appartements de standing. Travaux en cours : réfection toiture, création de trois accès indépendants, aménagement caves en espaces de rangement.',
    images: [],
    featured: true,
  },
  {
    id: 'immeuble-rapport-valenciennes',
    title: 'Immeuble de rapport — Valenciennes',
    location: 'Valenciennes, Hauts-de-France',
    type: 'Résidentiel',
    surface: '380 m²',
    units: 5,
    status: 'realise',
    buyPrice: '260 000 €',
    worksAmount: '85 000 €',
    sellPrice: '480 000 €',
    duration: '7 mois',
    description: 'Acquisition d\'un immeuble de 5 lots avec locataires en place. Rénovation progressive lot par lot au fil des libérations. Revente à un investisseur institutionnel après stabilisation locative complète.',
    images: [],
    featured: false,
  },
];
