export const PROPERTIES = [
  {
    id: 'appartement-t3-lille',
    title: 'Appartement T3 rénové — Lille',
    city: 'Lille',
    location: 'Lille, Hauts-de-France',
    type: 'Appartement',
    surface: '68 m²',
    rooms: 3,
    price: '185 000 €',
    priceNum: 185000,
    status: 'disponible',
    dpe: 'D',
    floor: '2e étage',
    tenancy: 'Libre',
    description: 'Appartement entièrement rénové au 2e étage d\'un immeuble de caractère. Séjour lumineux de 25 m², cuisine équipée ouverte, deux chambres, salle de bains refaite à neuf. Cave et place de stationnement en cour.',
    works: ['Réfection complète électricité', 'Salle de bains neuve', 'Cuisine équipée', 'Parquet massif poncé et vitrifié'],
    features: ['Parquet massif', 'Double vitrage', 'Cave', 'Cuisine équipée', 'Digicode'],
    photos: [],
  },
  {
    id: 'appartement-t2-tourcoing',
    title: 'Appartement T2 avec terrasse — Tourcoing',
    city: 'Tourcoing',
    location: 'Tourcoing, Hauts-de-France',
    type: 'Appartement',
    surface: '45 m²',
    rooms: 2,
    price: '120 000 €',
    priceNum: 120000,
    status: 'disponible',
    dpe: 'C',
    floor: 'Dernier étage',
    tenancy: 'Libre',
    description: 'T2 au dernier étage avec terrasse de 12 m². Prestations soignées : parquet chêne, menuiseries aluminium, VMC double flux. Idéal primo-accédant ou investissement locatif.',
    works: ['Menuiseries aluminium', 'VMC double flux', 'Parquet chêne massif', 'Terrasse étanchéifiée'],
    features: ['Terrasse 12 m²', 'Dernier étage', 'Parquet chêne', 'VMC double flux'],
    photos: [],
  },
  {
    id: 'local-professionnel-tourcoing',
    title: 'Local professionnel — Tourcoing',
    city: 'Tourcoing',
    location: 'Tourcoing, Hauts-de-France',
    type: 'Local mixte',
    surface: '55 m²',
    rooms: 2,
    price: '95 000 €',
    priceNum: 95000,
    status: 'disponible',
    dpe: 'E',
    floor: 'Rez-de-chaussée',
    tenancy: 'Libre',
    description: 'Local professionnel en rez-de-chaussée, accès PMR, vitrine sur rue passante. Convient pour cabinet libéral, bureau ou commerce de proximité. Entièrement remis à neuf.',
    works: ['Mise aux normes accessibilité PMR', 'Électricité refaite', 'Vitrine neuve', 'Climatisation installée'],
    features: ['Accès PMR', 'Vitrine sur rue', 'Fibre optique', 'Climatisation'],
    photos: [],
  },
  {
    id: 'appartement-t4-lille',
    title: 'Appartement T4 familial — Lille',
    city: 'Lille',
    location: 'Lille, Hauts-de-France',
    type: 'Appartement',
    surface: '92 m²',
    rooms: 4,
    price: '245 000 €',
    priceNum: 245000,
    status: 'vendu',
    dpe: 'D',
    floor: 'Duplex',
    tenancy: 'Libre',
    description: 'Grand T4 familial en duplex. Trois chambres, double séjour traversant, cuisine séparée aménagée. Garage en sous-sol et cave.',
    works: ['Rénovation complète', 'Isolation thermique', 'Cuisine aménagée', 'Garage sécurisé'],
    features: ['Duplex', 'Garage', 'Cave', 'Double séjour', 'Trois chambres'],
    photos: [],
  },
];
