export const PROPERTIES = [
  {
    id: 'appartement-t3-lille',
    title: 'Appartement T3 rénové — Lille',
    location: 'Lille, Hauts-de-France',
    type: 'Appartement',
    surface: '68 m²',
    rooms: 3,
    price: '185 000 €',
    status: 'a-vendre',
    description: 'Appartement entièrement rénové au 2e étage d\'un immeuble de caractère. Séjour lumineux de 25 m², cuisine équipée ouverte, deux chambres, salle de bains refaite à neuf. Cave et place de stationnement en cour.',
    features: ['Parquet massif', 'Double vitrage', 'Cave', 'Cuisine équipée', 'Digicode'],
    images: [],
  },
  {
    id: 'appartement-t2-tourcoing',
    title: 'Appartement T2 avec terrasse — Tourcoing',
    location: 'Tourcoing, Hauts-de-France',
    type: 'Appartement',
    surface: '45 m²',
    rooms: 2,
    price: '120 000 €',
    status: 'a-vendre',
    description: 'T2 au dernier étage avec terrasse de 12 m². Prestations soignées : parquet chêne, menuiseries aluminium, VMC double flux. Idéal primo-accédant ou investissement locatif.',
    features: ['Terrasse 12 m²', 'Dernier étage', 'Parquet chêne', 'VMC double flux'],
    images: [],
  },
  {
    id: 'local-professionnel-tourcoing',
    title: 'Local professionnel — Tourcoing',
    location: 'Tourcoing, Hauts-de-France',
    type: 'Local professionnel',
    surface: '55 m²',
    rooms: 2,
    price: '95 000 €',
    status: 'a-vendre',
    description: 'Local professionnel en rez-de-chaussée, accès PMR, vitrine sur rue passante. Convient pour cabinet libéral, bureau ou commerce de proximité. Entièrement remis à neuf.',
    features: ['Accès PMR', 'Vitrine sur rue', 'Fibre optique', 'Climatisation'],
    images: [],
  },
  {
    id: 'appartement-t4-lille',
    title: 'Appartement T4 familial — Lille',
    location: 'Lille, Hauts-de-France',
    type: 'Appartement',
    surface: '92 m²',
    rooms: 4,
    price: '245 000 €',
    status: 'vendu',
    description: 'Grand T4 familial en duplex. Trois chambres, double séjour traversant, cuisine séparée aménagée. Garage en sous-sol et cave.',
    features: ['Duplex', 'Garage', 'Cave', 'Double séjour', 'Trois chambres'],
    images: [],
  },
];
