export const PROPERTIES = [
  {
    id: 'appartement-t3-lille',
    title: 'Appartement T3 rénové — Lille',
    city: 'Lille',
    location: 'Lille, Hauts-de-France',
    neighborhood: 'Moulins',
    address: '10 rue des Muguets, 59000 Lille',
    nearbyTransport: 'Métro Porte de Douai (5 min), Gare Lille Flandres (12 min)',
    nearbyAmenities: 'Écoles, commerces, parc Jean-Baptiste Lebas',
    type: 'Appartement',
    surface: '68 m²',
    rooms: 3,
    price: '185 000 €',
    priceNum: 185000,
    priceNote: 'Prix net vendeur — frais de notaire en sus (~14 800 €)',
    status: 'disponible',
    dpe: 'D',
    dpeNote: 'Estimation charges énergétiques : ~900 €/an',
    floor: '2e étage',
    tenancy: 'Libre',
    renovationYear: '2024',
    charges: '120 €/mois',
    description: 'Appartement entièrement rénové au 2e étage d\'un immeuble de caractère. Séjour lumineux de 25 m², cuisine équipée ouverte, deux chambres, salle de bains refaite à neuf. Cave et place de stationnement en cour.',
    works: ['Réfection complète électricité', 'Salle de bains neuve', 'Cuisine équipée', 'Parquet massif poncé et vitrifié'],
    features: ['Parquet massif', 'Double vitrage', 'Cave', 'Cuisine équipée', 'Digicode'],
    photos: [],
  },
  {
    id: 'appartement-t2-tourcoing',
    title: 'Appartement T2 avec terrasse — Tourcoing',
    city: 'Tourcoing',
    location: 'Tourcoing, Hauts-de-France',
    neighborhood: 'Centre-ville',
    address: 'Rue de la Cloche, 59200 Tourcoing',
    nearbyTransport: 'Métro Tourcoing Centre (3 min), Tramway (5 min)',
    nearbyAmenities: 'Commerces, marché, parc Clemenceau',
    type: 'Appartement',
    surface: '45 m²',
    rooms: 2,
    price: '120 000 €',
    priceNum: 120000,
    priceNote: 'Prix net vendeur — frais de notaire en sus (~9 600 €)',
    status: 'disponible',
    dpe: 'C',
    dpeNote: 'Estimation charges énergétiques : ~650 €/an',
    floor: 'Dernier étage',
    tenancy: 'Libre',
    renovationYear: '2024',
    charges: '85 €/mois',
    description: 'T2 au dernier étage avec terrasse de 12 m². Prestations soignées : parquet chêne, menuiseries aluminium, VMC double flux. Idéal primo-accédant ou investissement locatif.',
    works: ['Menuiseries aluminium', 'VMC double flux', 'Parquet chêne massif', 'Terrasse étanchéifiée'],
    features: ['Terrasse 12 m²', 'Dernier étage', 'Parquet chêne', 'VMC double flux'],
    photos: [],
  },
  {
    id: 'local-professionnel-tourcoing',
    title: 'Local professionnel — Tourcoing',
    city: 'Tourcoing',
    location: 'Tourcoing, Hauts-de-France',
    neighborhood: 'Centre-ville',
    address: 'Avenue de la République, 59200 Tourcoing',
    nearbyTransport: 'Métro Tourcoing Centre (4 min)',
    nearbyAmenities: 'Axe passant, commerces, parking public',
    type: 'Local mixte',
    surface: '55 m²',
    rooms: 2,
    price: '95 000 €',
    priceNum: 95000,
    priceNote: 'Prix net vendeur — frais de notaire en sus (~7 600 €)',
    status: 'disponible',
    dpe: 'E',
    dpeNote: 'Estimation charges énergétiques : ~1 200 €/an',
    floor: 'Rez-de-chaussée',
    tenancy: 'Libre',
    renovationYear: '2024',
    charges: '65 €/mois',
    description: 'Local professionnel en rez-de-chaussée, accès PMR, vitrine sur rue passante. Convient pour cabinet libéral, bureau ou commerce de proximité. Entièrement remis à neuf.',
    works: ['Mise aux normes accessibilité PMR', 'Électricité refaite', 'Vitrine neuve', 'Climatisation installée'],
    features: ['Accès PMR', 'Vitrine sur rue', 'Fibre optique', 'Climatisation'],
    photos: [],
  },
  {
    id: 'appartement-t4-lille',
    title: 'Appartement T4 familial — Lille',
    city: 'Lille',
    location: 'Lille, Hauts-de-France',
    neighborhood: 'Bois-Blancs',
    address: 'Rue Colbert, 59000 Lille',
    nearbyTransport: 'Bus Liane 1 (2 min), Métro Bois Blancs (8 min)',
    nearbyAmenities: 'Écoles, parc de la Citadelle, commerces',
    type: 'Appartement',
    surface: '92 m²',
    rooms: 4,
    price: '245 000 €',
    priceNum: 245000,
    priceNote: 'Prix net vendeur',
    status: 'vendu',
    dpe: 'D',
    dpeNote: 'Estimation charges énergétiques : ~1 100 €/an',
    floor: 'Duplex',
    tenancy: 'Libre',
    renovationYear: '2023',
    charges: '150 €/mois',
    description: 'Grand T4 familial en duplex. Trois chambres, double séjour traversant, cuisine séparée aménagée. Garage en sous-sol et cave.',
    works: ['Rénovation complète', 'Isolation thermique', 'Cuisine aménagée', 'Garage sécurisé'],
    features: ['Duplex', 'Garage', 'Cave', 'Double séjour', 'Trois chambres'],
    photos: [],
  },
];
